---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-briefing-deployment
  namespace: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: the-briefing
  template:
    metadata:
      labels:
        app: the-briefing
    spec:
      containers:
      - name: the-briefing-container
        image: wiameelyakini/the-briefing:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: the-briefing-service
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: the-briefing
  ports:
  - port: 80
    targetPort: 3000
